version: '3.9'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: VoiceAIWrapperDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Dhruv123@
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    environment:
      DEBUG: "1"
      DATABASE_URL: postgres://pm:pm@db:5432/pm
      ALLOWED_HOSTS: "*"
      CORS_ALLOW_ORIGINS: http://localhost:5173
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    environment:
      VITE_API_URL: http://localhost:8000/graphql
      VITE_ORG_SLUG: demo-org
    ports:
      - "5173:5173"
    depends_on:
      - backend
volumes:
  dbdata: